import React from "react";
import {
  Globe,
  Terminal,
  Hash,
} from "lucide-react";
import { Layer, Document } from "@/types/scene";

export interface ComponentTemplate {
  id: string;
  name: string;
  category: string;
  icon: React.ElementType;
  description: string;
  createLayer: () => Layer;
}

export function getComponentTemplates(doc: Document): ComponentTemplate[] {
  return [
    {
      id: "comp_browser_window",
      name: "Browser Window Frame",
      category: "Frames",
      icon: Globe,
      description: "Safari/Chrome window with macOS traffic lights, URL search pill, and clipped viewport",
      createLayer: () => {
        const id = `browser_${Date.now()}`;
        return {
          id,
          name: "Browser Window",
          type: "group",
          style: {
            x: Math.round((doc.settings.width - 800) / 2),
            y: Math.round((doc.settings.height - 500) / 2),
            width: 800,
            height: 500,
            rotation: 0,
            opacity: 1,
            backgroundColor: "#18181b",
            borderRadius: 16,
            borderWidth: 1,
            borderColor: "rgba(255, 255, 255, 0.12)",
            shadowDistance: 24,
            shadowBlur: 48,
            shadowOpacity: 0.4,
          },
          animation: {
            in: {
              preset: "pop",
              start: 0,
              duration: 0.6,
              easing: "snappy",
            },
          },
          children: [
            {
              id: `${id}_dot_red`,
              name: "Close Dot",
              type: "shape",
              shapeType: "circle",
              style: {
                x: 16,
                y: 15,
                width: 12,
                height: 12,
                rotation: 0,
                opacity: 1,
                backgroundColor: "#ff5f56",
                borderRadius: 9999,
              },
            },
            {
              id: `${id}_dot_yellow`,
              name: "Minimize Dot",
              type: "shape",
              shapeType: "circle",
              style: {
                x: 34,
                y: 15,
                width: 12,
                height: 12,
                rotation: 0,
                opacity: 1,
                backgroundColor: "#ffbd2e",
                borderRadius: 9999,
              },
            },
            {
              id: `${id}_dot_green`,
              name: "Maximize Dot",
              type: "shape",
              shapeType: "circle",
              style: {
                x: 52,
                y: 15,
                width: 12,
                height: 12,
                rotation: 0,
                opacity: 1,
                backgroundColor: "#27c93f",
                borderRadius: 9999,
              },
            },
            {
              id: `${id}_url_pill`,
              name: "URL Pill",
              type: "text",
              content: "https://motion.studio",
              style: {
                x: 200,
                y: 9,
                width: 400,
                height: 24,
                rotation: 0,
                opacity: 0.85,
                fontSize: 11,
                fontWeight: 500,
                fontFamily: "Inter",
                color: "#a1a1aa",
                backgroundColor: "#27272a",
                borderRadius: 6,
                textAlign: "center",
              },
            },
            {
              id: `${id}_viewport`,
              name: "Content Viewport",
              type: "frame",
              clipContent: true,
              style: {
                x: 1,
                y: 42,
                width: 798,
                height: 456,
                rotation: 0,
                opacity: 1,
                backgroundColor: "#09090b",
                borderRadius: [0, 0, 16, 16],
              },
              children: [
                {
                  id: `${id}_content_text`,
                  name: "Headline",
                  type: "text",
                  content: "World-Class Motion Graphics",
                  style: {
                    x: 100,
                    y: 180,
                    width: 600,
                    height: "auto",
                    rotation: 0,
                    opacity: 1,
                    fontSize: 36,
                    fontWeight: 800,
                    fontFamily: "Inter",
                    color: "#ffffff",
                    textAlign: "center",
                  },
                  animation: {
                    in: {
                      preset: "slideUp",
                      start: 0.2,
                      duration: 0.6,
                      easing: "bouncy",
                    },
                  },
                },
              ],
            },
          ],
        };
      },
    },
    {
      id: "comp_kinetic_counter",
      name: "Kinetic Rolling Counter",
      category: "Typography",
      icon: Hash,
      description: "Mechanical rolling odometer counter ($0 → $125,000/mo) with bold showcase typography",
      createLayer: () => ({
        id: `counter_${Date.now()}`,
        name: "Kinetic Counter",
        type: "counter",
        startValue: 0,
        endValue: 125000,
        prefix: "$",
        suffix: "/mo",
        decimals: 0,
        useGrouping: true,
        counterMode: "odometer",
        odometerRoll: true,
        style: {
          x: Math.round((doc.settings.width - 500) / 2),
          y: Math.round((doc.settings.height - 120) / 2),
          width: 500,
          height: 120,
          rotation: 0,
          opacity: 1,
          fontSize: 76,
          fontWeight: 800,
          fontFamily: "Inter",
          color: "#ffffff",
          textAlign: "center",
        },
        animation: {
          in: {
            preset: "pop",
            start: 0,
            duration: 1.2,
            easing: "bouncy",
          },
        },
      }),
    },
    {
      id: "comp_code_window",
      name: "Code Block Window",
      category: "Dev",
      icon: Terminal,
      description: "macOS dark terminal snippet window with traffic lights and monospace syntax styling",
      createLayer: () => {
        const id = `code_${Date.now()}`;
        return {
          id,
          name: "Code Window",
          type: "group",
          style: {
            x: Math.round((doc.settings.width - 550) / 2),
            y: Math.round((doc.settings.height - 300) / 2),
            width: 550,
            height: 300,
            rotation: 0,
            opacity: 1,
            backgroundColor: "#0d1117",
            borderRadius: 14,
            borderWidth: 1,
            borderColor: "rgba(255, 255, 255, 0.1)",
            shadowDistance: 20,
            shadowBlur: 40,
            shadowOpacity: 0.5,
          },
          animation: {
            in: {
              preset: "pop",
              start: 0,
              duration: 0.6,
              easing: "bouncy",
            },
          },
          children: [
            {
              id: `${id}_dot_red`,
              name: "Dot Red",
              type: "shape",
              shapeType: "circle",
              style: {
                x: 14,
                y: 14,
                width: 10,
                height: 10,
                rotation: 0,
                opacity: 1,
                backgroundColor: "#ff5f56",
                borderRadius: 9999,
              },
            },
            {
              id: `${id}_dot_yellow`,
              name: "Dot Yellow",
              type: "shape",
              shapeType: "circle",
              style: {
                x: 30,
                y: 14,
                width: 10,
                height: 10,
                rotation: 0,
                opacity: 1,
                backgroundColor: "#ffbd2e",
                borderRadius: 9999,
              },
            },
            {
              id: `${id}_dot_green`,
              name: "Dot Green",
              type: "shape",
              shapeType: "circle",
              style: {
                x: 46,
                y: 14,
                width: 10,
                height: 10,
                rotation: 0,
                opacity: 1,
                backgroundColor: "#27c93f",
                borderRadius: 9999,
              },
            },
            {
              id: `${id}_filename`,
              name: "Filename",
              type: "text",
              content: "motion.config.ts",
              style: {
                x: 180,
                y: 10,
                width: 190,
                height: 20,
                rotation: 0,
                opacity: 0.6,
                fontSize: 11,
                fontWeight: 500,
                fontFamily: "Fira Code",
                color: "#8b949e",
                textAlign: "center",
              },
            },
            {
              id: `${id}_code_body`,
              name: "Code Content",
              type: "text",
              content: `const engine = new MotionEngine({\\n  fps: 60,\\n  physics: "spring",\\n  damping: 0.72,\\n  stiffness: 280\\n});`,
              style: {
                x: 24,
                y: 54,
                width: 502,
                height: "auto",
                rotation: 0,
                opacity: 1,
                fontSize: 16,
                fontWeight: 500,
                fontFamily: "Fira Code",
                color: "#7ee787",
                textAlign: "left",
                lineHeight: 1.5,
              },
              animation: {
                in: {
                  preset: "slideUp",
                  start: 0.3,
                  duration: 0.6,
                  easing: "smooth",
                },
              },
            },
          ],
        };
      },
    },
  ];
}
