import React from "react";
import {
  Globe,
  Smartphone,
  Laptop,
  Terminal,
  Hash,
  Sparkles,
  MousePointerClick,
  CreditCard,
  Square,
} from "lucide-react";
import { Layer, Document } from "@/types/scene";

export interface ComponentTemplate {
  id: string;
  name: string;
  category: string;
  icon: React.ElementType;
  description: string;
  createLayer: () => Layer;
}

export function getComponentTemplates(doc: Document): ComponentTemplate[] {
  return [
    {
      id: "comp_browser_window",
      name: "Browser Window Frame",
      category: "Frames",
      icon: Globe,
      description: "Safari/Chrome window with macOS traffic lights, URL search pill, and clipped viewport",
      createLayer: () => {
        const id = `browser_${Date.now()}`;
        return {
          id,
          name: "Browser Window",
          type: "group",
          style: {
            x: Math.round((doc.settings.width - 800) / 2),
            y: Math.round((doc.settings.height - 500) / 2),
            width: 800,
            height: 500,
            rotation: 0,
            opacity: 1,
            backgroundColor: "#18181b",
            borderRadius: 16,
            borderWidth: 1,
            borderColor: "rgba(255, 255, 255, 0.12)",
            shadowDistance: 24,
            shadowBlur: 48,
            shadowOpacity: 0.4,
          },
          animation: {
            in: {
              preset: "pop",
              start: 0,
              duration: 0.6,
              easing: "snappy",
            },
          },
          children: [
            {
              id: `${id}_dot_red`,
              name: "Close Dot",
              type: "shape",
              shapeType: "circle",
              style: {
                x: 16,
                y: 15,
                width: 12,
                height: 12,
                rotation: 0,
                opacity: 1,
                backgroundColor: "#ff5f56",
                borderRadius: 9999,
              },
            },
            {
              id: `${id}_dot_yellow`,
              name: "Minimize Dot",
              type: "shape",
              shapeType: "circle",
              style: {
                x: 34,
                y: 15,
                width: 12,
                height: 12,
                rotation: 0,
                opacity: 1,
                backgroundColor: "#ffbd2e",
                borderRadius: 9999,
              },
            },
            {
              id: `${id}_dot_green`,
              name: "Maximize Dot",
              type: "shape",
              shapeType: "circle",
              style: {
                x: 52,
                y: 15,
                width: 12,
                height: 12,
                rotation: 0,
                opacity: 1,
                backgroundColor: "#27c93f",
                borderRadius: 9999,
              },
            },
            {
              id: `${id}_url_pill`,
              name: "URL Pill",
              type: "text",
              content: "https://motion.studio",
              style: {
                x: 200,
                y: 9,
                width: 400,
                height: 24,
                rotation: 0,
                opacity: 0.85,
                fontSize: 11,
                fontWeight: 500,
                fontFamily: "Inter",
                color: "#a1a1aa",
                backgroundColor: "#27272a",
                borderRadius: 6,
                textAlign: "center",
              },
            },
            {
              id: `${id}_viewport`,
              name: "Content Viewport",
              type: "frame",
              clipContent: true,
              style: {
                x: 1,
                y: 42,
                width: 798,
                height: 456,
                rotation: 0,
                opacity: 1,
                backgroundColor: "#09090b",
                borderRadius: [0, 0, 16, 16],
              },
              children: [
                {
                  id: `${id}_content_text`,
                  name: "Headline",
                  type: "text",
                  content: "World-Class Motion Graphics",
                  style: {
                    x: 100,
                    y: 180,
                    width: 600,
                    height: "auto",
                    rotation: 0,
                    opacity: 1,
                    fontSize: 36,
                    fontWeight: 800,
                    fontFamily: "Inter",
                    color: "#ffffff",
                    textAlign: "center",
                  },
                  animation: {
                    in: {
                      preset: "slideUp",
                      start: 0.2,
                      duration: 0.6,
                      easing: "bouncy",
                    },
                  },
                },
              ],
            },
          ],
        };
      },
    },
    {
      id: "comp_iphone_mockup",
      name: "iPhone 16 Pro 3D",
      category: "3D Mockups",
      icon: Smartphone,
      description: "Three.js PBR iPhone 16 Pro mockup with telephoto camera and natural titanium finish",
      createLayer: () => ({
        id: `iphone_${Date.now()}`,
        name: "iPhone 16 Pro",
        type: "mockup3d",
        modelType: "iphone",
        deviceFinish: "natural-titanium",
        position3D: [0, 0, 0],
        rotation3D: [0, -0.2, 0],
        scale3D: [1, 1, 1],
        cameraPreset: "orbit360",
        cameraFov: 32,
        cameraPosition: [0, 0, 5],
        cameraTarget: [0, 0, 0],
        specularSweep: true,
        style: {
          x: Math.round((doc.settings.width - 500) / 2),
          y: Math.round((doc.settings.height - 700) / 2),
          width: 500,
          height: 700,
          rotation: 0,
          opacity: 1,
        },
        animation: {
          in: {
            preset: "pop",
            start: 0,
            duration: 0.8,
            easing: "bouncy",
          },
        },
      }),
    },
    {
      id: "comp_macbook_mockup",
      name: "MacBook Pro 3D",
      category: "3D Mockups",
      icon: Laptop,
      description: "Three.js PBR MacBook Pro mockup with telephoto camera and space black finish",
      createLayer: () => ({
        id: `macbook_${Date.now()}`,
        name: "MacBook Pro",
        type: "mockup3d",
        modelType: "macbook",
        deviceFinish: "space-black",
        position3D: [0, -0.2, 0],
        rotation3D: [0.15, 0.35, 0],
        scale3D: [1, 1, 1],
        cameraPreset: "isometric",
        cameraFov: 35,
        cameraPosition: [0, 0.5, 4.5],
        cameraTarget: [0, 0, 0],
        specularSweep: true,
        style: {
          x: Math.round((doc.settings.width - 700) / 2),
          y: Math.round((doc.settings.height - 500) / 2),
          width: 700,
          height: 500,
          rotation: 0,
          opacity: 1,
        },
        animation: {
          in: {
            preset: "slideUp",
            start: 0,
            duration: 0.8,
            easing: "snappy",
          },
        },
      }),
    },
    {
      id: "comp_kinetic_counter",
      name: "Kinetic Rolling Counter",
      category: "Typography",
      icon: Hash,
      description: "Mechanical rolling odometer counter ($0 → $125,000/mo) with bold showcase typography",
      createLayer: () => ({
        id: `counter_${Date.now()}`,
        name: "Kinetic Counter",
        type: "counter",
        startValue: 0,
        endValue: 125000,
        prefix: "$",
        suffix: "/mo",
        decimals: 0,
        useGrouping: true,
        counterMode: "odometer",
        odometerRoll: true,
        style: {
          x: Math.round((doc.settings.width - 500) / 2),
          y: Math.round((doc.settings.height - 120) / 2),
          width: 500,
          height: 120,
          rotation: 0,
          opacity: 1,
          fontSize: 76,
          fontWeight: 800,
          fontFamily: "Inter",
          color: "#ffffff",
          textAlign: "center",
        },
        animation: {
          in: {
            preset: "pop",
            start: 0,
            duration: 1.2,
            easing: "bouncy",
          },
        },
      }),
    },
    {
      id: "comp_code_window",
      name: "Code Block Window",
      category: "Dev",
      icon: Terminal,
      description: "macOS dark terminal snippet window with traffic lights and monospace syntax styling",
      createLayer: () => {
        const id = `code_${Date.now()}`;
        return {
          id,
          name: "Code Window",
          type: "group",
          style: {
            x: Math.round((doc.settings.width - 550) / 2),
            y: Math.round((doc.settings.height - 300) / 2),
            width: 550,
            height: 300,
            rotation: 0,
            opacity: 1,
            backgroundColor: "#0d1117",
            borderRadius: 14,
            borderWidth: 1,
            borderColor: "rgba(255, 255, 255, 0.1)",
            shadowDistance: 20,
            shadowBlur: 40,
            shadowOpacity: 0.5,
          },
          animation: {
            in: {
              preset: "pop",
              start: 0,
              duration: 0.6,
              easing: "bouncy",
            },
          },
          children: [
            {
              id: `${id}_dot_red`,
              name: "Dot Red",
              type: "shape",
              shapeType: "circle",
              style: {
                x: 14,
                y: 14,
                width: 10,
                height: 10,
                rotation: 0,
                opacity: 1,
                backgroundColor: "#ff5f56",
                borderRadius: 9999,
              },
            },
            {
              id: `${id}_dot_yellow`,
              name: "Dot Yellow",
              type: "shape",
              shapeType: "circle",
              style: {
                x: 30,
                y: 14,
                width: 10,
                height: 10,
                rotation: 0,
                opacity: 1,
                backgroundColor: "#ffbd2e",
                borderRadius: 9999,
              },
            },
            {
              id: `${id}_dot_green`,
              name: "Dot Green",
              type: "shape",
              shapeType: "circle",
              style: {
                x: 46,
                y: 14,
                width: 10,
                height: 10,
                rotation: 0,
                opacity: 1,
                backgroundColor: "#27c93f",
                borderRadius: 9999,
              },
            },
            {
              id: `${id}_filename`,
              name: "Filename",
              type: "text",
              content: "motion.config.ts",
              style: {
                x: 180,
                y: 10,
                width: 190,
                height: 20,
                rotation: 0,
                opacity: 0.6,
                fontSize: 11,
                fontWeight: 500,
                fontFamily: "Fira Code",
                color: "#8b949e",
                textAlign: "center",
              },
            },
            {
              id: `${id}_code_body`,
              name: "Code Content",
              type: "text",
              content: `const engine = new MotionEngine({\\n  fps: 60,\\n  physics: "spring",\\n  damping: 0.72,\\n  stiffness: 280\\n});`,
              style: {
                x: 24,
                y: 54,
                width: 502,
                height: "auto",
                rotation: 0,
                opacity: 1,
                fontSize: 16,
                fontWeight: 500,
                fontFamily: "Fira Code",
                color: "#7ee787",
                textAlign: "left",
                lineHeight: 1.5,
              },
              animation: {
                in: {
                  preset: "slideUp",
                  start: 0.3,
                  duration: 0.6,
                  easing: "smooth",
                },
              },
            },
          ],
        };
      },
    },
    {
      id: "comp_hero_card",
      name: "Hero Message Card",
      category: "Cards",
      icon: Sparkles,
      description: "Auto-fitting dark card with 3 staggered kinetic typography chunks",
      createLayer: () => ({
        id: `hero_card_${Date.now()}`,
        name: "Hero Card",
        type: "group",
        layout: {
          display: "flex",
          flexDirection: "column",
          gap: 20,
          align: "center",
          justifyContent: "center",
        },
        autoFit: true,
        autoLink: true,
        staggerDelay: 0.15,
        style: {
          x: doc.settings.width / 2 - 400,
          y: doc.settings.height / 2 - 200,
          width: 800,
          height: "auto",
          rotation: 0,
          opacity: 1,
          backgroundColor: "#18181b",
          padding: 48,
          borderRadius: 20,
          borderWidth: 1,
          borderColor: "rgba(255, 255, 255, 0.1)",
          shadows: [
            {
              x: 0,
              y: 25,
              blur: 50,
              spread: -10,
              color: "rgba(0,0,0,0.8)",
            },
          ],
        },
        children: [
          {
            id: `chunk_1_${Date.now()}`,
            name: "Hey Team,",
            type: "text",
            content: "Hey Team,",
            style: {
              x: 0,
              y: 0,
              width: "auto",
              height: "auto",
              rotation: 0,
              opacity: 1,
              fontSize: 68,
              fontWeight: 800,
              fontFamily: "Inter",
              color: "#FFFFFF",
              textAlign: "center",
              lineHeight: 1.1,
            },
            animation: {
              in: {
                preset: "pop",
                start: 0.0,
                duration: 0.6,
                easing: "bouncy",
              },
            },
          },
          {
            id: `chunk_2_${Date.now()}`,
            name: "I've got something big",
            type: "text",
            content: "I've got something big for you all,",
            style: {
              x: 0,
              y: 0,
              width: "auto",
              height: "auto",
              rotation: 0,
              opacity: 1,
              fontSize: 54,
              fontWeight: 800,
              fontFamily: "Inter",
              color: "#60A5FA",
              textAlign: "center",
              lineHeight: 1.1,
            },
            animation: {
              in: {
                preset: "slideUp",
                start: 0.8,
                duration: 0.6,
                easing: "smooth",
              },
            },
          },
          {
            id: `chunk_3_${Date.now()}`,
            name: "wanna see what it is?",
            type: "text",
            content: "wanna see what it is?",
            style: {
              x: 0,
              y: 0,
              width: "auto",
              height: "auto",
              rotation: 0,
              opacity: 1,
              fontSize: 54,
              fontWeight: 800,
              fontFamily: "Inter",
              color: "#FACC15",
              textAlign: "center",
              lineHeight: 1.1,
            },
            animation: {
              in: {
                preset: "blurIn",
                start: 1.6,
                duration: 0.8,
                easing: "smooth",
              },
            },
          },
        ],
      }),
    },
    {
      id: "comp_neon_button",
      name: "Gold Stamp Button",
      category: "Buttons",
      icon: MousePointerClick,
      description: "Pill button with glowing Stamp Gold and pop-in entrance",
      createLayer: () => ({
        id: `btn_${Date.now()}`,
        name: "Gold Stamp Button",
        type: "text",
        content: "Get Started Free →",
        style: {
          x: doc.settings.width / 2 - 130,
          y: doc.settings.height / 2 - 30,
          width: "auto",
          height: "auto",
          rotation: 0,
          opacity: 1,
          fontSize: 24,
          fontWeight: 700,
          fontFamily: "Inter",
          color: "#0a0a0a",
          backgroundColor: "#e8c547",
          padding: [14, 28, 14, 28],
          borderRadius: 9999,
          shadows: [
            { x: 0, y: 10, blur: 25, spread: -5, color: "rgba(232,197,71,0.5)" },
          ],
        },
        animation: {
          in: {
            preset: "pop",
            start: 0,
            duration: 0.6,
            easing: "bouncy",
          },
        },
      }),
    },
    {
      id: "comp_glass_card",
      name: "Glassmorphism Card",
      category: "Cards",
      icon: CreditCard,
      description: "Translucent backdrop blurred container with slide entrance",
      createLayer: () => ({
        id: `glass_card_${Date.now()}`,
        name: "Glassmorphism Card",
        type: "group",
        layout: {
          display: "flex",
          flexDirection: "column",
          gap: 12,
          align: "center",
          justifyContent: "center",
        },
        autoFit: true,
        autoLink: true,
        staggerDelay: 0.15,
        style: {
          x: doc.settings.width / 2 - 200,
          y: doc.settings.height / 2 - 120,
          width: 400,
          height: "auto",
          rotation: 0,
          opacity: 1,
          backgroundColor: "rgba(17, 17, 17, 0.85)",
          backdropBlur: 20,
          padding: 32,
          borderRadius: 24,
          borderWidth: 1,
          borderColor: "rgba(238, 232, 213, 0.15)",
          shadows: [
            { x: 0, y: 20, blur: 40, spread: -10, color: "rgba(0,0,0,0.6)" },
          ],
        },
        children: [
          {
            id: `glass_title_${Date.now()}`,
            name: "Card Title",
            type: "text",
            content: "Night Workshop UI",
            style: {
              x: 0,
              y: 0,
              width: "auto",
              height: "auto",
              rotation: 0,
              opacity: 1,
              fontSize: 32,
              fontWeight: 800,
              fontFamily: "Inter",
              color: "#eee8d5",
            },
            animation: {
              in: {
                preset: "pop",
                start: 0,
                duration: 0.5,
                easing: "smooth",
              },
            },
          },
        ],
        animation: {
          in: {
            preset: "slideUp",
            start: 0,
            duration: 0.6,
            easing: "smooth",
          },
        },
      }),
    },
    {
      id: "comp_squircle_surface",
      name: "G2 Squircle Surface",
      category: "Surfaces",
      icon: Square,
      description: "Continuous curvature surface with physical elevation shadow",
      createLayer: () => ({
        id: `surface_${Date.now()}`,
        name: "Squircle Surface",
        type: "shape",
        shapeType: "rectangle",
        style: {
          x: doc.settings.width / 2 - 200,
          y: doc.settings.height / 2 - 150,
          width: 400,
          height: 300,
          rotation: 0,
          opacity: 1,
          backgroundColor: "#18181b",
          borderRadius: 28,
          squircleFactor: 0.6,
          elevation: 2,
          shadowDistance: 16,
          shadowBlur: 32,
          shadowOpacity: 0.3,
        },
        animation: {
          in: {
            preset: "slideUp",
            start: 0,
            duration: 0.6,
            easing: "snappy",
          },
        },
      }),
    },
  ];
}
